package com.example.a24_03_toile.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF815600)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB1)
val md_theme_light_onPrimaryContainer = Color(0xFF291800)
val md_theme_light_secondary = Color(0xFFB90063)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF3E001D)
val md_theme_light_tertiary = Color(0xFF00687A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFACEDFF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F26)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFF80847C)
val md_theme_light_onBackground = Color(0xFF082100)
val md_theme_light_surface = Color(0xFFF7FFEC)
val md_theme_light_onSurface = Color(0xFF082100)
val md_theme_light_surfaceVariant = Color(0xFFEFE0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_inverseOnSurface = Color(0xFFCEFFAE)
val md_theme_light_inverseSurface = Color(0xFF133800)
val md_theme_light_inversePrimary = Color(0xFFFEBA4B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF815600)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFEBA4B)
val md_theme_dark_onPrimary = Color(0xFF442B00)
val md_theme_dark_primaryContainer = Color(0xFF614000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB1)
val md_theme_dark_secondary = Color(0xFFFFB1C8)
val md_theme_dark_onSecondary = Color(0xFF650033)
val md_theme_dark_secondaryContainer = Color(0xFF8E004A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_tertiary = Color(0xFF55D6F4)
val md_theme_dark_onTertiary = Color(0xFF003640)
val md_theme_dark_tertiaryContainer = Color(0xFF004E5C)
val md_theme_dark_onTertiaryContainer = Color(0xFFACEDFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF082100)
val md_theme_dark_onBackground = Color(0xFFB9F396)
val md_theme_dark_surface = Color(0xFF082100)
val md_theme_dark_onSurface = Color(0xFFB9F396)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9B8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF082100)
val md_theme_dark_inverseSurface = Color(0xFFB9F396)
val md_theme_dark_inversePrimary = Color(0xFF815600)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFEBA4B)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF815600)
